name: release-arm64-linux

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    runs-on: linux-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: NAME=clang+llvm-16.0.3-aarch64-linux-gnu ./build.sh

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./clang+llvm-16.0.3-aarch64-linux-gnu.tar.xz
