name: release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    strategy:
      matrix:
        go_os: [darwin]
        go_arch: [arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build
        run: NAME=clang+llvm-16.0.3-arm64-apple-darwin22.0.tar.xz ./build.sh

      - name: Release artifact
        uses: softprops/action-gh-release@v1
        with:
          files: ./clang+llvm-16.0.3-arm64-apple-darwin22.0.tar.xz
